language: node_js
sudo: false

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

install:
  - npm install -g codecov
  - npm install
before_script: npm run build
script:
  - npm run cover  
  - codecov
